### ISSUE TITLE
Please add support for Storage Access Framework

### ISSUE THREAD

**Issue by akshay7692** [hexise/jaudiotagger-android#1]
Without Storage Access Framework, it is not possible to write tags in SD card songs on Android 4.4 and higher.

**Comment by hexise** [comment]
This can be done outside of this library. I prefer only modify this library if necessary.

**Comment by akshay7692** [comment]
With Storage Access Framework (SAF) introduced from Android 4.4, SD card IO operations can only be to be carried out via SAF API using a DocumentFile object. How can I modify tags if library only accepts File object ?

**Comment by hexise** [comment]
You can make a copy of your original file and save tags modification to it, and copy it back to external SD card.

**Comment by theoklink** [comment]
@hexise
can you help?
 I am trying to do just that by replacing musicFile.commit();. 
I have the complete process working, apart from actually updating the file with the new tag data. 
I have the new changed tag
flac_musicFile.setTag(flactag);
then
 File newSourceFile = flac_musicFile.getFile();
followed by 
creating a copy with underscore as prefix eg \_fullpathtotrack
String outputFile= "\_"+inputFile;
write the file out
DocumentFile newFile = pickedDir.createFile("audio/" + extension, outputFile);
out = context.getContentResolver().openOutputStream(newFile.getUri());
then delete original and rename the _fullpathtotrack to original trackname
It all works as expected apart from the tag changes 
What step am I missing
